import test from 'node:test';import assert from 'node:assert/strict';
import {getGameRoomRules} from '../src/game-room-rules.mjs';
import {buildOnlineRoomMatch} from '../src/game-history.mjs';
import {vaultEdges,scores} from '../../preview-v4/src/modules/games/gold-vault/gold-vault-engine.js';
import {createOnlineGameSession} from '../../preview-v4/src/modules/games/online/game-online-session.js';
import {createGameRoomResumeStore} from '../../preview-v4/src/modules/games/online/game-room-resume-store.js';
const rules=getGameRoomRules('gold-vault');
function storage(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}
test('uses existing room registry and validates two-player capacity',()=>{const s=rules.createInitialState('a',{displayName:'ياسر'});assert.equal(s.status,'waiting');assert.equal(rules.maxPlayers,2);assert.equal(rules.addPlayer(s,'a').reason,'player-already-in-room');const joined=rules.addPlayer(s,'b',{displayName:'خالد'});assert.equal(joined.state.status,'playing');assert.equal(rules.addPlayer(joined.state,'c').ok,false);assert.equal(rules.applyAction(joined.state,{playerId:'b',type:'roll'}).reason,'not-your-turn');});
test('two existing online sessions create, join, synchronize moves and resume; rejects stale version',async()=>{
 let state,version=0;const players=[{playerId:'a',learnerId:'yasser',name:'ياسر',seat:0},{playerId:'b',learnerId:'khaled',name:'خالد',seat:1}];const room=id=>({code:'123456',gameId:'gold-vault',status:state.status,version,state:structuredClone(state),players:state.players.length===1?players.slice(0,1):players,selfPlayerId:id});
 const client={async createRoom(){state=rules.createInitialState('a');return {room:room('a'),playerToken:'host-token-long-enough'};},async joinRoom(){state=rules.addPlayer(state,'b').state;version++;return {room:room('b'),playerToken:'guest-token-long-enough'};},async getRoom({token}){return {room:room(token.startsWith('host')?'a':'b')};},async submitAction({token,expectedVersion,type,payload}){const id=token.startsWith('host')?'a':'b';if(expectedVersion!==version){const e=new Error('stale');e.status=409;e.body={room:room(id)};throw e;}const r=rules.applyAction(state,{playerId:id,type,payload});if(!r.ok)throw new Error(r.reason);state=r.state;version++;return {room:room(id)};}};
 const make=()=>createOnlineGameSession({gameId:'gold-vault',roomClient:client,autoPoll:false,resumeStore:createGameRoomResumeStore({gameId:'gold-vault',sessionStorage:storage(),localStorage:storage()})});const host=make(),guest=make();await host.create('yasser');await guest.join('123456','khaled');await host.refresh();await assert.rejects(()=>guest.submit('roll'),/not-your-turn/);await host.submit('roll');await guest.refresh();assert.deepEqual(host.snapshot.room.state,guest.snapshot.room.state);await host.submit('edge',{edgeId:'h-0-0'});await assert.rejects(()=>guest.submit('edge',{edgeId:'h-0-1'}),/stale/);assert.deepEqual(host.snapshot.room.state,guest.snapshot.room.state);host.stop();assert.equal(host.hasResume('yasser'),true);await host.resume({learnerId:'yasser'});assert.equal(host.snapshot.room.state.edges['h-0-0'],'a');host.stop();guest.stop();
});
test('completed online game is recorded with correct winners and points',()=>{let s=rules.addPlayer(rules.createInitialState('a'),'b').state;for(const edge of vaultEdges()){let id=s.players[s.turnIndex].id;if(s.phase==='roll'){s=rules.applyAction(s,{playerId:id,type:'roll'}).state;}s=rules.applyAction(s,{playerId:id,type:'edge',payload:{edgeId:edge.id}}).state;}
 const r=buildOnlineRoomMatch({roomRow:{id:'room-1',game_id:'gold-vault',history_family_id:'family-1',code:'123456',created_at:s.startedAt},players:[{player_id:'a',learner_id:'yasser',display_name:'ياسر',seat:0},{player_id:'b',learner_id:'khaled',display_name:'خالد',seat:1}],state:s,version:60});assert.equal(r.ok,true);const match=r.match||r.value||r;assert.equal(match.playMode,'online');assert.equal(match.players.reduce((a,p)=>a+p.score,0),16);
});
