import test from 'node:test';
import assert from 'node:assert/strict';
import {planDominoChain} from '../src/modules/games/domino/domino-chain-layout.js';
const tile=(left,right)=>({left,right});
function boundsOf(p,w,h){const vertical=p.rotation%180!==0;const width=(vertical?h:w)*p.scale,height=(vertical?w:h)*p.scale;return {left:p.x-width/2,right:p.x+width/2,top:p.y-height/2,bottom:p.y+height/2};}
function touches(a,b,w,h){const A=boundsOf(a,w,h),B=boundsOf(b,w,h);const gapX=Math.max(0,Math.max(A.left,B.left)-Math.min(A.right,B.right));const gapY=Math.max(0,Math.max(A.top,B.top)-Math.min(A.bottom,B.bottom));return gapX<.05&&gapY<.05;}
test('anchor stays centered as chain grows',()=>{const o={width:680,height:360,tileWidth:82,tileHeight:44};for(const [tiles,anchor] of [[[tile(6,6)],0],[[tile(6,5),tile(6,6)],1],[[tile(6,5),tile(6,6),tile(6,2)],1]]){const p=planDominoChain({...o,tiles,anchorIndex:anchor});assert.equal(p.placements[anchor].x,340);assert.equal(p.placements[anchor].y,180);}});
test('opening double is horizontal',()=>{const p=planDominoChain({tiles:[tile(6,6)],anchorIndex:0,width:500,height:300,tileWidth:82,tileHeight:44});assert.equal(p.placements[0].rotation%180,0);});
test('later doubles are perpendicular to local path',()=>{const tiles=[tile(6,4),tile(4,4),tile(4,3),tile(3,2),tile(2,2),tile(2,1),tile(1,0)];const p=planDominoChain({tiles,anchorIndex:3,width:680,height:360,tileWidth:82,tileHeight:44});for(const [i,t] of tiles.entries())if(i!==3&&t.left===t.right)assert.equal((p.placements[i].rotation-p.placements[i].pathRotation+360)%180,90);});
test('every consecutive tile stays physically connected through turns and doubles',()=>{const tiles=[tile(0,0),tile(0,1),tile(1,2),tile(2,2),tile(2,3),tile(3,4),tile(4,4),tile(4,5),tile(5,6),tile(6,6),tile(6,3),tile(3,3),tile(3,1),tile(1,1),tile(1,4),tile(4,6),tile(6,2),tile(2,5),tile(5,5),tile(5,0),tile(0,2),tile(2,4),tile(4,0),tile(0,3),tile(3,5),tile(5,1),tile(1,6),tile(6,0)];const p=planDominoChain({tiles,anchorIndex:13,width:680,height:360,tileWidth:82,tileHeight:44});for(let i=0;i<p.placements.length-1;i++)assert.equal(touches(p.placements[i],p.placements[i+1],82,44),true,`gap at ${i}-${i+1}`);});
test('full double-six stays inside phone tablet and desktop boards without horizontal scroll',()=>{const tiles=[];for(let l=0;l<=6;l++)for(let r=l;r<=6;r++)tiles.push(tile(l,r));for(const v of [{width:300,height:300},{width:680,height:360},{width:900,height:280}]){const p=planDominoChain({...v,tiles,anchorIndex:14,tileWidth:82,tileHeight:44,padding:6});assert.equal(p.placements.length,28);assert.ok(new Set(p.placements.map(x=>x.row)).size>1);for(const x of p.placements){const b=boundsOf(x,82,44);assert.ok(b.left>=5.9);assert.ok(b.right<=v.width-5.9);assert.ok(b.top>=5.9);assert.ok(b.bottom<=v.height-5.9);}}});
