import test from 'node:test';
import assert from 'node:assert/strict';
import {planDominoChain} from '../src/modules/games/domino/domino-chain-layout.js';
const tile=(left,right)=>({left,right});
function boundsOf(placement,tileWidth,tileHeight){const vertical=placement.rotation%180!==0;const width=(vertical?tileHeight:tileWidth)*placement.scale,height=(vertical?tileWidth:tileHeight)*placement.scale;return {left:placement.x-width/2,right:placement.x+width/2,top:placement.y-height/2,bottom:placement.y+height/2};}
test('anchor remains stable when the chain grows on either side',()=>{const options={width:320,height:210,tileWidth:70,tileHeight:38};const single=planDominoChain({...options,tiles:[tile(1,2)],anchorIndex:0});const leftGrowth=planDominoChain({...options,tiles:[tile(0,1),tile(1,2)],anchorIndex:1});const rightGrowth=planDominoChain({...options,tiles:[tile(1,2),tile(2,3)],anchorIndex:0});assert.deepEqual([single.placements[0].x,single.placements[0].y],[leftGrowth.placements[1].x,leftGrowth.placements[1].y]);assert.deepEqual([single.placements[0].x,single.placements[0].y],[rightGrowth.placements[0].x,rightGrowth.placements[0].y]);});
test('long chains turn inside the board instead of requiring horizontal scroll',()=>{const tiles=Array.from({length:20},(_,index)=>tile(index%7,(index+1)%7));const plan=planDominoChain({tiles,anchorIndex:10,width:320,height:250,tileWidth:70,tileHeight:38,minScale:.6});assert.equal(plan.placements.length,tiles.length);assert.ok(plan.placements.some(item=>item.pathRotation===90));assert.ok(new Set(plan.placements.map(item=>item.row)).size>1);});
test('doubles stay perpendicular to the local chain direction',()=>{const plan=planDominoChain({tiles:[tile(5,5)],anchorIndex:0,width:320,height:210,tileWidth:70,tileHeight:38});const placement=plan.placements[0];assert.equal((placement.rotation-placement.pathRotation+360)%180,90);});
test('full double-six capacity stays inside mobile and desktop board bounds',()=>{const tiles=[];for(let left=0;left<=6;left++)for(let right=left;right<=6;right++)tiles.push(tile(left,right));for(const viewport of [{width:280,height:220},{width:320,height:250},{width:600,height:250},{width:900,height:230}]){const plan=planDominoChain({...viewport,tiles,anchorIndex:14,tileWidth:70,tileHeight:38,padding:6,minScale:.6});assert.equal(plan.placements.length,28);for(const placement of plan.placements){const bounds=boundsOf(placement,70,38);assert.ok(bounds.left>=5.9);assert.ok(bounds.right<=viewport.width-5.9);assert.ok(bounds.top>=5.9);assert.ok(bounds.bottom<=viewport.height-5.9);}}});
