import test from 'node:test';import assert from 'node:assert/strict';
import {createVaultState,applyVaultAction,vaultEdges,previewVaultEdge,scores,restoreVaultState} from '../src/modules/games/gold-vault/gold-vault-engine.js';
const players=[{id:'a',name:'ياسر'},{id:'b',name:'خالد'}];
const apply=(s,type,payload={},die=()=>6)=>{const r=applyVaultAction(s,{playerId:s.players[s.turnIndex].id,type,payload},{die});assert.equal(r.ok,true,r.reason);return r.state;};
function complete(die=()=>3){let s=createVaultState(players);for(const edge of vaultEdges()){if(s.phase==='roll')s=apply(s,'roll',{},die);s=apply(s,'edge',{edgeId:edge.id});assert.ok(restoreVaultState(s));}return s;}
test('board has 25 nodes, 16 cells and 40 unique edges',()=>{assert.equal(vaultEdges().length,40);assert.equal(new Set(vaultEdges().map(e=>e.id)).size,40);assert.equal(createVaultState(players).remaining,0);});
test('rejects wrong turn, line before roll, repeated roll and duplicate edge without mutation',()=>{let s=createVaultState(players);assert.equal(applyVaultAction(s,{playerId:'b',type:'roll'}).reason,'not-your-turn');assert.equal(applyVaultAction(s,{playerId:'a',type:'edge',payload:{edgeId:'h-0-0'}}).reason,'roll-first');s=apply(s,'roll');assert.equal(applyVaultAction(s,{playerId:'a',type:'roll'}).reason,'already-rolled');const n=apply(s,'edge',{edgeId:'h-0-0'});assert.deepEqual(s.edges,{});assert.equal(applyVaultAction(n,{playerId:'a',type:'edge',payload:{edgeId:'h-0-0'}}).reason,'occupied-edge');assert.equal(n.remaining,5);});
test('one line captures two adjacent cells and preview does not mutate',()=>{let s=createVaultState(players);s.phase='place';s.remaining=2;for(const id of ['h-0-0','h-1-0','v-0-0','h-0-1','h-1-1','v-0-2'])s.edges[id]='b';s.moveCount=6;assert.deepEqual(previewVaultEdge(s,'v-0-1'),['0-0','0-1']);assert.deepEqual(s.cells,{});const n=apply(s,'edge',{edgeId:'v-0-1'});assert.deepEqual(scores(n),{a:2,b:0});assert.equal(n.remaining,1);assert.equal(n.turnIndex,0);assert.equal(n.lastEvent.captured.length,2);});
test('capturing on final available line still passes dice turn without bonus',()=>{let s=createVaultState(players);s.phase='place';s.remaining=1;s.edges={'h-0-0':'b','h-1-0':'a','v-0-0':'a'};s.moveCount=3;const n=apply(s,'edge',{edgeId:'v-0-1'});assert.equal(n.cells['0-0'],'a');assert.equal(n.turnIndex,1);assert.equal(n.phase,'roll');assert.equal(n.remaining,0);});
test('thinking mode retains turn only after capture',()=>{let s=createVaultState(players,{mode:'thinking'});s.edges={'h-0-0':'b','h-1-0':'a','v-0-0':'a'};s.moveCount=3;const n=apply(s,'edge',{edgeId:'v-0-1'});assert.equal(n.turnIndex,0);assert.equal(n.remaining,1);});
test('full round owns every cell, scores total 16, ends and alternates rematch starter',()=>{const s=complete();assert.equal(s.status,'finished');assert.equal(s.moveCount,40);assert.equal(Object.keys(s.cells).length,16);assert.equal(Object.values(scores(s)).reduce((a,b)=>a+b),16);assert.equal(s.remaining,0);assert.equal(applyVaultAction(s,{playerId:'a',type:'edge',payload:{edgeId:'v-3-4'}}).reason,'game-not-playing');const a=applyVaultAction(s,{playerId:'a',type:'reset'}).state;assert.equal(a.status,'finished');assert.equal(applyVaultAction(a,{playerId:'a',type:'reset'}).reason,'rematch-already-ready');const b=applyVaultAction(a,{playerId:'b',type:'reset'}).state;assert.equal(b.round,2);assert.equal(b.turnIndex,1);assert.equal(b.moveCount,0);});
test('restoration rejects corrupted ownership, missing edges and counters',()=>{const s=complete();assert.ok(restoreVaultState(JSON.parse(JSON.stringify(s))));assert.equal(restoreVaultState({...s,moveCount:1}),null);assert.equal(restoreVaultState({...s,cells:{...s.cells,'0-0':'intruder'}}),null);const edges={...s.edges};delete edges['h-0-0'];assert.equal(restoreVaultState({...s,edges,moveCount:39}),null);});
test('dice truncates to remaining legal edges and ignores client supplied die value',()=>{let s=createVaultState(players);const edges=vaultEdges();for(const edge of edges.slice(0,-1)){if(s.phase==='roll')s=apply(s,'roll');s=apply(s,'edge',{edgeId:edge.id});}assert.equal(s.phase,'place');assert.equal(s.remaining,1);const first=applyVaultAction(createVaultState(players),{playerId:'a',type:'roll',payload:{value:6}},{die:()=>2}).state;assert.equal(first.dice,2);});
test('100 varied rounds preserve integrity and score ownership after every move',()=>{let seed=17;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let n=0;n<100;n++){let s=createVaultState(players);while(s.status==='playing'){if(s.phase==='roll')s=apply(s,'roll',{},()=>1+Math.floor(rand()*6));const available=vaultEdges().filter(e=>!s.edges[e.id]);s=apply(s,'edge',{edgeId:available[Math.floor(rand()*available.length)].id});assert.ok(restoreVaultState(s));assert.equal(Object.values(scores(s)).reduce((a,b)=>a+b),Object.keys(s.cells).length);}assert.equal(s.moveCount,40);}});
