import {createQuestionRecord} from '../../../shared/question-bank/index.js';
import {YASSER_SCIENCE_BOOK_SOURCE,YASSER_SCIENCE_BOOK_VISUAL_ASSETS} from './science-book-visuals.generated.js';

// الصور المعروضة لياسر مقتطفات مباشرة من كتاب العلوم نفسه، بدون إعادة رسم.
export const YASSER_SCIENCE_VISUAL_ASSETS=YASSER_SCIENCE_BOOK_VISUAL_ASSETS;

const scope=Object.freeze({subjectId:'science',gradeId:'grade-6',termId:'term-1',curriculumYear:'1448',unitId:'unit-1-diversity-of-life',chapterId:'chapter-1-cells'});
const textbook=Object.freeze({...YASSER_SCIENCE_BOOK_SOURCE,year:'1448',examType:'textbook'});
const q=(input)=>createQuestionRecord({...scope,difficulty:input.difficulty||2,tags:['science','grade-6','term-1','unit-1','chapter-1','visual','textbook-exact','answer-verified'],verified:true,...input,sources:[textbook]});

export const YASSER_SCIENCE_VISUAL_QUESTIONS=Object.freeze([
  q({id:'science:visual:plant-cell-vacuole',topicId:'plant-animal-cell',conceptId:'vacuole',type:'choice',assetId:'plant-cell-parts',prompt:'في صورة الخلية النباتية من الكتاب، أي تركيب يخزن الماء ومواد أخرى ويكون كبيرًا نسبيًا؟',choices:['الفجوة','النواة','الميتوكندريا','الغشاء البلازمي'],answer:'الفجوة',explanation:'الفجوة في الخلية النباتية كبيرة نسبيًا وتخزن الماء ومواد أخرى.'}),
  q({id:'science:visual:animal-cell-nucleus',topicId:'plant-animal-cell',conceptId:'nucleus',type:'choice',assetId:'animal-cell-parts',prompt:'في صورة الخلية الحيوانية من الكتاب، أي جزء يحتوي معظم المعلومات الوراثية؟',choices:['النواة','الفجوة','الميتوكندريا','الغشاء البلازمي'],answer:'النواة',explanation:'النواة تحتوي معظم المعلومات الوراثية وتتحكم في كثير من أنشطة الخلية.'}),
  q({id:'science:visual:cell-wall-layer',topicId:'plant-animal-cell',conceptId:'cell-wall',type:'choice',assetId:'cell-wall-membrane',prompt:'بالنظر إلى صورة الخلية النباتية، أي تركيب خارجي يدعم الخلية ويحميها؟',choices:['الجدار الخلوي','النواة','الفجوة','الميتوكندريا'],answer:'الجدار الخلوي',explanation:'الجدار الخلوي تركيب خارجي قوي يدعم الخلية النباتية ويحميها.'}),
  q({id:'science:visual:chloroplast-identify',topicId:'plant-animal-cell',conceptId:'chloroplast',type:'choice',assetId:'chloroplast-closeup',prompt:'أي تركيب في الصورة يحتوي على الكلوروفيل ويساعد النبات على صنع غذائه؟',choices:['البلاستيدة الخضراء','الميتوكندريا','النواة','الفجوة'],answer:'البلاستيدة الخضراء',explanation:'البلاستيدات الخضراء تحتوي الكلوروفيل وتشارك في البناء الضوئي.'}),
  q({id:'science:visual:mitochondria-identify',topicId:'plant-animal-cell',conceptId:'mitochondria',type:'choice',assetId:'mitochondria-closeup',prompt:'أي جزء في الصورة يعرف بأنه مركز إنتاج الطاقة في الخلية؟',choices:['الميتوكندريا','البلاستيدة الخضراء','الفجوة','الجدار الخلوي'],answer:'الميتوكندريا',explanation:'الميتوكندريا موقع رئيس للتنفس الخلوي وإطلاق الطاقة.'}),
  q({id:'science:visual:nucleus-identify',topicId:'plant-animal-cell',conceptId:'nucleus',type:'choice',assetId:'nucleus-closeup',prompt:'أي جزء في الصورة يعد مركز التحكم في الخلية ويحتوي معظم معلوماتها الوراثية؟',choices:['النواة','الجدار الخلوي','الغشاء البلازمي','الفجوة'],answer:'النواة',explanation:'النواة مركز التحكم وتحتوي معظم المعلومات الوراثية.'}),
  q({id:'science:visual:vacuole-identify',topicId:'plant-animal-cell',conceptId:'vacuole',type:'choice',assetId:'vacuole-plant',prompt:'في صورة الخلية النباتية، ما التركيب الكبير الذي يخزن الماء ومواد أخرى؟',choices:['الفجوة','النواة','الجدار الخلوي','الميتوكندريا'],answer:'الفجوة',explanation:'تكون الفجوة في الخلية النباتية كبيرة نسبيًا.'}),
  q({id:'science:visual:diffusion-direction',topicId:'cell-processes',conceptId:'diffusion',type:'choice',assetId:'diffusion-gradient',prompt:'الصورة من الكتاب توضح انتقال جسيمات من تركيز مرتفع إلى تركيز منخفض. ما هذه العملية؟',choices:['الانتشار','النقل النشط','البناء الضوئي','التنفس الخلوي'],answer:'الانتشار',explanation:'في الانتشار تتحرك الجسيمات من التركيز الأعلى إلى التركيز الأقل.'}),
  q({id:'science:visual:osmosis-water',topicId:'cell-processes',conceptId:'osmosis',type:'choice',assetId:'osmosis-membrane',prompt:'أي مادة تنتقل عبر الغشاء في الخاصية الأسموزية الموضحة في الكتاب؟',choices:['الماء','البروتين','النشا','الدهون'],answer:'الماء',explanation:'الأسموزية هي انتقال جزيئات الماء عبر الغشاء.'}),
  q({id:'science:visual:active-energy',topicId:'cell-processes',conceptId:'active-transport',type:'choice',assetId:'active-transport-energy',prompt:'أي نوع من النقل عبر الغشاء يحتاج إلى طاقة من الخلية؟',choices:['النقل النشط','النقل السلبي','الانتشار','الأسموزية'],answer:'النقل النشط',explanation:'النقل النشط يحتاج إلى طاقة لنقل المواد عبر الغشاء.'}),
  q({id:'science:visual:passive-no-energy',topicId:'cell-processes',conceptId:'passive-transport',type:'choice',assetId:'passive-transport',prompt:'أي نوع من النقل الموضح في الكتاب لا يحتاج إلى طاقة من الخلية؟',choices:['النقل السلبي','النقل النشط','البناء الضوئي','التنفس الخلوي'],answer:'النقل السلبي',explanation:'النقل السلبي لا يحتاج إلى طاقة من الخلية.'}),
  q({id:'science:visual:photosynthesis-identify',topicId:'cell-processes',conceptId:'photosynthesis-products',type:'choice',assetId:'photosynthesis-flow',prompt:'الصورة من الكتاب توضح استخدام الضوء والماء وثاني أكسيد الكربون لصنع الغذاء. ما العملية؟',choices:['البناء الضوئي','التنفس الخلوي','الأسموزية','النقل النشط'],answer:'البناء الضوئي',explanation:'في البناء الضوئي يستخدم النبات الضوء والماء وثاني أكسيد الكربون لصنع الغذاء وإطلاق الأكسجين.'}),
  q({id:'science:visual:respiration-identify',topicId:'cell-processes',conceptId:'cellular-respiration',type:'choice',assetId:'respiration-flow',prompt:'الصورة من الكتاب توضح عملية تطلق الطاقة من الغذاء داخل الخلية. ما العملية؟',choices:['التنفس الخلوي','البناء الضوئي','الأسموزية','الانتشار'],answer:'التنفس الخلوي',explanation:'التنفس الخلوي يطلق الطاقة من الغذاء داخل الخلية.'}),
  q({id:'science:visual:water-percent',topicId:'cell-chemistry',conceptId:'water-in-cells',type:'choice',assetId:'water-cell-components',prompt:'وفق الشكل في الكتاب، ما المادة التي تشكل النسبة الأكبر من مكونات خلايا الإنسان؟',choices:['الماء','البروتينات','الدهون','الأملاح'],answer:'الماء',explanation:'يوضح الشكل في الدرس أن الماء يشكل نحو 70% من مكونات خلايا الإنسان.'}),
  q({id:'science:visual:tissue-types',topicId:'organization-levels',conceptId:'tissue-types',type:'choice',assetId:'tissues',prompt:'الصور في الكتاب تعرض أمثلة لأنسجة مختلفة. ما تعريف النسيج؟',choices:['مجموعة خلايا متشابهة تقوم بالوظيفة نفسها','مجموعة أعضاء تعمل معًا','مخلوق حي كامل','جزء داخل النواة'],answer:'مجموعة خلايا متشابهة تقوم بالوظيفة نفسها',explanation:'النسيج مجموعة من الخلايا المتشابهة تقوم بالوظيفة نفسها.'})
]);
