import {createQuestionRecord} from '../../../shared/question-bank/index.js';
import {YASSER_SCIENCE_BOOK_SOURCE,YASSER_SCIENCE_BOOK_VISUAL_ASSETS} from './science-book-visuals.generated.js';

// صور الفصل الأول هنا قصاصات مباشرة ومراجعة بصريًا من كتاب العلوم نفسه.
export const YASSER_SCIENCE_VISUAL_ASSETS=YASSER_SCIENCE_BOOK_VISUAL_ASSETS;

const scope=Object.freeze({subjectId:'science',gradeId:'grade-6',termId:'term-1',curriculumYear:'1448',unitId:'unit-1-diversity-of-life',chapterId:'chapter-1-cells'});
const textbook=Object.freeze({...YASSER_SCIENCE_BOOK_SOURCE,year:'1448',examType:'textbook'});
const q=(input)=>createQuestionRecord({...scope,difficulty:input.difficulty||2,tags:['science','grade-6','term-1','unit-1','chapter-1','visual','textbook-exact','answer-verified'],verified:true,...input,sources:[textbook]});

export const YASSER_SCIENCE_VISUAL_QUESTIONS=Object.freeze([
  q({id:'science:visual:cell-summary',topicId:'cells',conceptId:'cell-theory',type:'choice',assetId:'cell-summary',prompt:'الصورة من مفردات الكتاب تمثل الوحدة الأساسية للحياة. ما هي؟',choices:['الخلية','النسيج','العضو','الجهاز الحيوي'],answer:'الخلية',explanation:'الخلية هي الوحدة الأساسية للحياة.'}),
  q({id:'science:visual:tissue-summary',topicId:'organization-levels',conceptId:'tissue',type:'choice',assetId:'tissue-summary',prompt:'ما تعريف النسيج الذي تمثله الصورة؟',choices:['مجموعة خلايا متشابهة تقوم بالوظيفة نفسها','مجموعة أعضاء تعمل معًا','جزء واحد من الخلية','مخلوق حي كامل'],answer:'مجموعة خلايا متشابهة تقوم بالوظيفة نفسها',explanation:'النسيج مجموعة من الخلايا المتشابهة التي تقوم بالوظيفة نفسها.'}),
  q({id:'science:visual:organ-system-summary',topicId:'organization-levels',conceptId:'organ-system',type:'choice',assetId:'organ-system-summary',prompt:'الصورة في مفردات الكتاب مثال على أي مستوى من مستويات التنظيم؟',choices:['جهاز حيوي','عضو','نسيج','خلية'],answer:'جهاز حيوي',explanation:'الجهاز الحيوي مجموعة من الأعضاء التي تعمل معًا لأداء وظيفة محددة.'}),
  q({id:'science:visual:passive-summary',topicId:'cell-processes',conceptId:'passive-transport',type:'choice',assetId:'passive-transport-summary',prompt:'ما العملية التي يوضحها الرسم وتنتقل فيها المواد عبر الغشاء دون حاجة إلى طاقة؟',choices:['النقل السلبي','النقل النشط','البناء الضوئي','التنفس الخلوي'],answer:'النقل السلبي',explanation:'النقل السلبي يحدث دون حاجة الخلية إلى طاقة.'}),
  q({id:'science:visual:osmosis-summary',topicId:'cell-processes',conceptId:'osmosis',type:'choice',assetId:'osmosis-summary',prompt:'الصورة توضح انتقال جزيئات الماء عبر الغشاء البلازمي. ما العملية؟',choices:['الخاصية الأسموزية','النقل النشط','التنفس الخلوي','البناء الضوئي'],answer:'الخاصية الأسموزية',explanation:'الخاصية الأسموزية هي انتقال جزيئات الماء عبر الغشاء البلازمي.'}),
  q({id:'science:visual:active-summary',topicId:'cell-processes',conceptId:'active-transport',type:'choice',assetId:'active-transport-summary',prompt:'ما نوع النقل الذي يوضحه الرسم ويحتاج إلى طاقة من الخلية؟',choices:['النقل النشط','النقل السلبي','الانتشار','الخاصية الأسموزية'],answer:'النقل النشط',explanation:'النقل النشط يحتاج إلى طاقة لنقل المواد عبر الغشاء.'}),
  q({id:'science:visual:volvox',topicId:'cells',conceptId:'unicellular-multicellular',type:'choice',assetId:'volvox',prompt:'ما اسم المستعمرة الظاهرة في الصورة كما وردت في الكتاب؟',choices:['الفولفكس','البراميسيوم','الأميبا','البكتيريا'],answer:'الفولفكس',explanation:'الصورة تعرض مستعمرة الفولفكس.'}),
  q({id:'science:visual:paramecium',topicId:'cells',conceptId:'unicellular',type:'choice',assetId:'paramecium',prompt:'البراميسيوم الظاهر في الصورة مثال على مخلوق:',choices:['وحيد الخلية','عديد الخلايا','يتكون من أنسجة','يتكون من أعضاء'],answer:'وحيد الخلية',explanation:'يذكر الكتاب أن البراميسيوم مخلوق وحيد الخلية يعيش في الماء.'}),
  q({id:'science:visual:tissue-types',topicId:'organization-levels',conceptId:'tissue-types',type:'choice',assetId:'tissue-types',prompt:'أي نوع من الأنسجة الظاهرة في الصورة ينقل الرسائل في الجسم؟',choices:['النسيج العصبي','النسيج العضلي','النسيج الضام','النسيج الطلائي'],answer:'النسيج العصبي',explanation:'النسيج العصبي ينقل الرسائل في الجسم.'}),
  q({id:'science:visual:animal-cell',topicId:'cells',conceptId:'animal-cell',type:'choice',assetId:'animal-cell',prompt:'في رسم الخلية الحيوانية من الكتاب، أي جزء يحتوي معظم المعلومات الوراثية؟',choices:['النواة','الفجوة','الميتوكندريا','الغشاء البلازمي'],answer:'النواة',explanation:'النواة تحتوي معظم المعلومات الوراثية في الخلية.'}),
  q({id:'science:visual:plant-cell',topicId:'cells',conceptId:'plant-cell',type:'choice',assetId:'plant-cell',prompt:'في رسم الخلية النباتية من الكتاب، أي تركيب خارجي يدعم الخلية ويحميها؟',choices:['الجدار الخلوي','النواة','الفجوة','الميتوكندريا'],answer:'الجدار الخلوي',explanation:'الجدار الخلوي يحيط بالخلية النباتية ويدعمها ويحميها.'}),
  q({id:'science:visual:osmosis-large',topicId:'cell-processes',conceptId:'osmosis',type:'choice',assetId:'osmosis-large',prompt:'الرسم يبين حركة جزيئات الماء حول النبات. ما العملية الموضحة؟',choices:['الخاصية الأسموزية','النقل النشط','البناء الضوئي','التنفس الخلوي'],answer:'الخاصية الأسموزية',explanation:'الصورة في الكتاب توضح الخاصية الأسموزية وحركة جزيئات الماء.'}),
  q({id:'science:visual:diffusion-large',topicId:'cell-processes',conceptId:'diffusion',type:'choice',assetId:'diffusion-large',prompt:'الرسم يوضح انتقال الجسيمات من منطقة تركيز مرتفع إلى منطقة تركيز منخفض. ما العملية؟',choices:['الانتشار','النقل النشط','البناء الضوئي','التنفس الخلوي'],answer:'الانتشار',explanation:'في الانتشار تتحرك الجسيمات من التركيز الأعلى إلى التركيز الأقل.'}),
  q({id:'science:visual:photosynthesis-diagram',topicId:'cell-processes',conceptId:'photosynthesis-inputs',type:'choice',assetId:'photosynthesis-diagram',prompt:'وفق مخطط البناء الضوئي في الكتاب، ما المادتان اللتان تدخلان في العملية مع طاقة الشمس؟',choices:['الماء وثاني أكسيد الكربون','الأكسجين والجلوكوز','الماء والأكسجين','الجلوكوز وثاني أكسيد الكربون'],answer:'الماء وثاني أكسيد الكربون',explanation:'يستخدم النبات الماء وثاني أكسيد الكربون مع طاقة الشمس في البناء الضوئي.'}),
  q({id:'science:visual:photo-resp-table',topicId:'cell-processes',conceptId:'photosynthesis-respiration',type:'choice',assetId:'photosynthesis-respiration-table',prompt:'وفق جدول المقارنة في الصورة، أي عملية تنتج الأكسجين وتخزن الطاقة في صورة جلوكوز؟',choices:['البناء الضوئي','التنفس الخلوي','الانتشار','النقل النشط'],answer:'البناء الضوئي',explanation:'البناء الضوئي ينتج الأكسجين ويخزن الطاقة في صورة جلوكوز.'}),
  q({id:'science:visual:photo-resp-cycle',topicId:'cell-processes',conceptId:'photosynthesis-respiration',type:'choice',assetId:'photosynthesis-respiration-cycle',prompt:'ماذا يوضح المخطط الدائري بين البناء الضوئي والتنفس الخلوي؟',choices:['نواتج كل عملية تُستخدم في العملية الأخرى','العمليتان تحدثان في الحيوان فقط','العمليتان لا ترتبطان ببعضهما','كلتاهما تحتاج ضوء الشمس دائمًا'],answer:'نواتج كل عملية تُستخدم في العملية الأخرى',explanation:'يوضح المخطط تبادل المواد بين البناء الضوئي والتنفس الخلوي.'}),
  q({id:'science:visual:amoeba-engulfing',topicId:'cell-processes',conceptId:'engulfing',type:'choice',assetId:'amoeba-engulfing',prompt:'كيف تحصل الأميبا الظاهرة في الصورة على الغذاء؟',choices:['تحيط به بغشائها البلازمي','تصنعه بالبناء الضوئي','تمتصه بالجدار الخلوي','تنتجه داخل النواة'],answer:'تحيط به بغشائها البلازمي',explanation:'تبتلع الأميبا الغذاء عن طريق إحاطته بجزء من الغشاء البلازمي.'}),
  q({id:'science:visual:active-transport-large',topicId:'cell-processes',conceptId:'active-transport',type:'choice',assetId:'active-transport-large',prompt:'في الرسم، تنتقل المواد من منطقة تركيز منخفض إلى منطقة تركيز مرتفع وتستهلك الخلية طاقة. ما العملية؟',choices:['النقل النشط','النقل السلبي','الانتشار','الخاصية الأسموزية'],answer:'النقل النشط',explanation:'النقل النشط ينقل مواد عكس تدرج التركيز ويحتاج إلى طاقة.'})
]);
