import {storageKeyFor,gradeReviewAnswer as gradeAnswer,summarizeReview as summarize,encouragement as motivationFor,summarizeHistory} from './review-engine.js';
import {createFeedbackAudio} from '../../../ui/audio/feedback-audio.js';
export function createReviewController(REVIEW){
const MATH_QUESTIONS=REVIEW.questions,SOURCES=REVIEW.sources;
const reviewHistorySummary=history=>summarizeHistory(history,MATH_QUESTIONS);
const feedbackAudio=createFeedbackAudio();
const KEY=storageKeyFor(REVIEW.id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view,onBack,state,warning='';
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.version===1&&Array.isArray(saved.history)){const a=saved.active;if(REVIEW.id==='math'&&a&&!a.finished&&a.ids?.length===15&&a.ids.every(id=>MATH_QUESTIONS.some(q=>q.id===id&&q.source.kind==='worksheet'))){a.ids=MATH_QUESTIONS.map(q=>q.id);}return saved;}return {version:1,active:null,history:[]};}catch{warning='تعذر قراءة الحفظ؛ تقدم هذه الجلسة سيبقى متاحًا أثناء فتح الصفحة.';return{version:1,active:null,history:[]};}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{warning='تعذر حفظ التقدم على هذا الجهاز. لا تغلق الصفحة قبل إكمال المحاولة.';}}
function questions(){return state.active.ids.map(id=>MATH_QUESTIONS.find(q=>q.id===id));}
function links(page){return `<div class="review-sources"><a href="${SOURCES.questions}#page=${page||1}" target="_blank" rel="noopener">المراجعة غير المحلولة${page?' · صفحة '+page:''}</a><a href="${SOURCES.answers}#page=${page||1}" target="_blank" rel="noopener">المراجعة المحلولة${page?' · صفحة '+page:''}</a></div>`;}
function base(content){view.innerHTML=`<div class="review-toolbar"><button id="reviewBack" type="button">رجوع لمواد ياسر</button><button id="reviewSound" type="button" aria-pressed="${state.sound!==false}">الصوت: ${state.sound===false?'مكتوم':'مفعّل'}</button></div><p>ياسر · سادس ابتدائي · ${esc(REVIEW.label)}</p>${warning?`<p role="alert">${warning}</p>`:''}${content}`;view.querySelector('#reviewBack').onclick=()=>{save();view.classList.remove('active');onBack?.();};view.querySelector('#reviewSound').onclick=()=>{state.sound=state.sound===false;save();const b=view.querySelector('#reviewSound');b.textContent=state.sound?'الصوت: مفعّل':'الصوت: مكتوم';b.setAttribute('aria-pressed',String(state.sound));};}
function focus(){view.querySelector('h1,h2')?.focus();}
function start(mode,ids=MATH_QUESTIONS.map(q=>q.id)){state.active={mode,ids,index:0,responses:{},drafts:{},startedAt:new Date().toISOString(),finished:false};save();render();focus();}
function home(){const last=state.history.at(-1);base(`<h1 tabindex="-1">مراجعة ${esc(REVIEW.label)}</h1><p>تمارين المراجعة وأسئلة من تعاريفها وشرحها فقط، والإجابات من النسخة المحلولة.</p><div class="review-panel"><h2>جاهز يا ياسر؟</h2><p>${MATH_QUESTIONS.length} سؤالًا · تمارين وتعريفات · نقطة لكل سؤال كامل · المقاليات تُقيّم بالمقارنة بالنموذج</p><div class="review-actions"><button id="train" class="review-primary">تدرّب</button><button id="exam">اختبر نفسك</button><button id="openHistory">سجل مراجعة ${esc(REVIEW.label)}</button>${state.active&&!state.active.finished?'<button id="resume">أكمل محاولتك المحفوظة</button>':''}</div><p>في التدريب تظهر الإجابة فورًا. في الاختبار تظهر الحلول بعد إنهائه.</p></div>${last?`<div class="review-panel"><h2>آخر نتيجة</h2><p>${last.mode==='exam'?'اختبار':'تدريب'} · ${new Date(last.finishedAt).toLocaleString('ar-SA')}</p><strong class="review-score">${last.summary.correct} / ${last.summary.total}</strong><p>أفضل اختبار: ${Math.max(0,...state.history.filter(h=>h.mode==='exam').map(h=>h.summary.percent))}٪</p><button id="lastResult">راجع النتيجة</button></div>`:''}${links()}`);view.querySelector('#train').onclick=()=>start('train');view.querySelector('#exam').onclick=()=>start('exam');view.querySelector('#openHistory').onclick=()=>{historyScreen();focus();};view.querySelector('#resume')?.addEventListener('click',()=>{render();focus();});view.querySelector('#lastResult')?.addEventListener('click',()=>result(last));}
function historyScreen(filter='all'){
 const stats=reviewHistorySummary(state.history);
 const entries=state.history.map((a,index)=>({a,index})).filter(({a})=>a.finished&&a.summary&&(filter==='all'||a.mode===filter)).reverse();
 base(`<h1 tabindex="-1">سجل ياسر · مراجعة ${esc(REVIEW.label)}</h1><p>كل محاولات هذه المراجعة محفوظة هنا على هذا الجهاز.</p><div class="review-panel"><div class="review-history-stats"><div><strong>${stats.total}</strong><span>محاولات مكتملة</span></div><div><strong>${stats.bestFullExam===null?'—':stats.bestFullExam+'٪'}</strong><span>أفضل اختبار كامل · ${MATH_QUESTIONS.length} سؤالًا</span></div></div>${stats.improvement!==null?`<p>${stats.improvement>0?'كفو يا ياسر! تحسنت '+stats.improvement+' نقطة مئوية':stats.improvement===0?'حافظت على نتيجتك، واصل يا ياسر!':'المحاولة القادمة فرصة تتحسن يا ياسر.'} مقارنة بالاختبار الكامل السابق.</p>`:''}<div class="review-actions" aria-label="تصفية سجل المحاولات">${[['all','الكل'],['train','التدريب'],['exam','الاختبارات']].map(([value,label])=>`<button data-history-filter="${value}" aria-pressed="${filter===value}">${label}</button>`).join('')}</div></div>${entries.length?entries.map(({a,index})=>`<article class="review-panel"><h2>${a.mode==='exam'?'اختبار':'تدريب'} · ${a.ids.length===MATH_QUESTIONS.length?'المراجعة كاملة':a.ids.length===15?'محاولة من ١٥ سؤالًا':'جولة من '+a.ids.length+' سؤالًا'}</h2><time datetime="${esc(a.finishedAt)}">${esc(new Date(a.finishedAt).toLocaleString('ar-SA'))}</time><p class="review-history-score">${a.summary.correct} / ${a.summary.total} · ${a.summary.percent}٪</p><p>صحيح: ${a.summary.correct} · خطأ: ${a.summary.wrong} · متروك: ${a.summary.unanswered}</p><button data-history-result="${index}">راجع إجابات المحاولة</button></article>`).join(''):'<div class="review-panel"><h2>ابدأ أول محاولة يا ياسر</h2><p>بعد إنهائها، تظهر درجتك وإجاباتك في السجل.</p></div>'}<div class="review-actions"><button id="historyHome" class="review-primary">رجوع لمراجعة ${esc(REVIEW.label)}</button></div>`);
 view.querySelector('#historyHome').onclick=()=>{home();focus();};
 for(const b of view.querySelectorAll('[data-history-filter]'))b.onclick=()=>historyScreen(b.dataset.historyFilter);
 for(const b of view.querySelectorAll('[data-history-result]'))b.onclick=()=>{result(state.history[Number(b.dataset.historyResult)]);focus();};
}
function questionGraphic(q){return `${q.expression?`<div class="review-expression">${esc(q.expression)}</div>`:''}${q.image?`<img class="review-chart" src="${REVIEW.assetBase}/${q.image}" alt="${esc(q.alt)}" width="744" loading="eager"/>`:''}${q.table?'<table class="review-table"><caption>قاعدة الدالة: س + ٣</caption><thead><tr><th scope="col">المدخلة</th><th scope="col">قاعدة الدالة</th><th scope="col">المخرجة</th></tr></thead><tbody><tr><td>٥</td><td>........</td><td>........</td></tr><tr><td>٦</td><td>........</td><td>........</td></tr></tbody></table>':''}`;}
function selfReviewControls(q){return `<div class="review-actions"><button data-self-review="${q.id}" data-correct="true">إجابتي توافق النموذج</button><button data-self-review="${q.id}" data-correct="false">أحتاج أراجع الإجابة</button></div>`;}
function bindSelfReview(a){for(const b of view.querySelectorAll('[data-self-review]'))b.onclick=()=>{const r=a.responses[b.dataset.selfReview];if(!r?.pending)return;r.correct=[b.dataset.correct==='true'];r.pending=false;r.selfReviewed=true;r.message=motivationFor(a.responses);if(state.sound!==false){try{r.correct[0]?feedbackAudio.correct():feedbackAudio.wrong();}catch{}}if(a.finished){a.summary=summarize(a.ids.map(id=>MATH_QUESTIONS.find(q=>q.id===id)),a.responses);const h=state.history.find(h=>h.startedAt===a.startedAt);if(h&&h!==a){h.responses=JSON.parse(JSON.stringify(a.responses));h.summary={...a.summary};}if(state.active?.startedAt===a.startedAt){state.active.responses=JSON.parse(JSON.stringify(a.responses));state.active.summary={...a.summary};}}save();a.finished?result(a):render();};}
function render(){const a=state.active;if(!a)return home();if(a.finished)return result(a);const qs=questions(),q=qs[a.index],r=a.responses[q.id],draft=a.drafts[q.id]||[];const answered=Object.keys(a.responses).length;const locked=!!r;const s=summarize(qs,a.responses);base(`<div class="review-meta"><span>${a.mode==='exam'?'اختبار':'تدريب'}</span><span>السؤال ${a.index+1} من ${qs.length}</span><span>${esc(q.topic)}</span><span>${q.source.kind==='review-content'?'من تعريفات وشرح المراجعة':'تمرين المراجعة الأصلي'}</span><span>أجبت ${answered} / ${qs.length}</span>${a.mode==='train'?`<span>صحيح: ${s.correct} · خطأ: ${s.wrong}${s.pending?' · بانتظار التقييم: '+s.pending:''}</span>`:''}</div><progress class="review-progress" value="${answered}" max="${qs.length}" aria-label="تقدم المحاولة"></progress><article class="review-panel"><h2 tabindex="-1" ${q.lang==='en'?'dir="ltr" lang="en"':''}>${esc(q.prompt)}</h2>${q.contextImage?`<details class="review-reading"><summary>اقرأ النص من المراجعة</summary><img src="${REVIEW.assetBase}/${q.contextImage}" alt="النص الأصلي من المراجعة"/></details>`:''}${questionGraphic(q)}${q.sourceIssue?`<p class="review-feedback" role="note">${esc(q.sourceIssue)}</p>${links(q.page)}`:''}<form id="answerForm" ${q.sourceIssue?'hidden':''}>${q.choices?`<div class="review-choices" role="group" aria-label="خيارات الإجابة">${q.choices.map(c=>`<button type="button" class="review-choice" aria-pressed="${(r?.values[0]??draft[0])===c}" data-choice="${esc(c)}" ${locked?'disabled':''}>${esc(c)}</button>`).join('')}</div><input type="hidden" id="answer0" value="${esc(r?.values[0]??draft[0]??'')}">`:`<div class="review-fields">${q.fields.map((f,i)=>`<label for="answer${i}">${esc(f.label)}<input id="answer${i}" autocomplete="off" ${q.math||q.lang==='en'?'dir="ltr"':''} value="${esc(r?.values[i]??draft[i]??'')}" ${locked?'disabled':''} required></label>`).join('')}</div>`}<div class="review-actions"><button type="submit" class="review-primary" ${locked?'disabled':''}>${a.mode==='train'?'تحقق من إجابتي':'ثبّت الإجابة'}</button></div><div id="answerNotice" role="status" aria-live="polite"></div></form>${r?(a.mode==='train'?`<div class="review-feedback ${r.pending?'pending':r.correct.every(Boolean)?'correct':'wrong'}" role="status"><strong>${esc(r.pending?'قارن إجابتك بالنموذج يا ياسر، ثم قيّمها.':r.message||(r.correct.every(Boolean)?'كفو يا ياسر، إجابة صحيحة!':'صحصح يا ياسر، راجع إجابتك!'))}</strong><br>${q.fields.map(f=>`${esc(f.label)}: ${esc(f.answer)}`).join('<br>')}${q.source.quote?`<p class="review-source-quote">من المراجعة: ${esc(q.source.quote)}</p>`:''}</div>${q.selfReview&&r.pending?selfReviewControls(q):''}${links(q.page)}`:'<p role="status">تم حفظ إجابتك. الحل يظهر بعد إنهاء الاختبار.</p>'):''}</article><div class="review-actions"><button id="previous" ${a.index===0?'disabled':''}>السابق</button><button id="next">${a.index===qs.length-1?'إنهاء المحاولة':r?'التالي':'تخطي الآن'}</button><button id="saveExit">حفظ وخروج</button></div>`);
const inputs=q.fields.map((_,i)=>view.querySelector('#answer'+i));const collect=()=>inputs.map(el=>el.value);for(const input of inputs)input.addEventListener('input',()=>{a.drafts[q.id]=collect();save();});for(const b of view.querySelectorAll('[data-choice]'))b.onclick=()=>{inputs[0].value=b.dataset.choice;a.drafts[q.id]=collect();save();for(const c of view.querySelectorAll('[data-choice]'))c.setAttribute('aria-pressed',String(c===b));};view.querySelector('#answerForm').onsubmit=e=>{e.preventDefault();if(a.responses[q.id])return;const values=collect();if(values.some(v=>!v.trim())){view.querySelector('#answerNotice').textContent='أكمل الإجابة أولًا.';return;}a.responses[q.id]={values,correct:q.selfReview?[]:gradeAnswer(q,values),pending:!!q.selfReview};a.responses[q.id].message=motivationFor(a.responses);if(!q.selfReview&&a.mode==='train'&&state.sound!==false){try{if(a.responses[q.id].correct.every(Boolean))feedbackAudio.correct();else feedbackAudio.wrong();}catch{}}save();render();};bindSelfReview(a);view.querySelector('#previous').onclick=()=>{a.index--;save();render();focus();};view.querySelector('#next').onclick=()=>{if(a.index===qs.length-1){const remaining=qs.filter(q=>!q.sourceIssue&&!a.responses[q.id]);if(remaining.length){base(`<h2 tabindex="-1">باقي ${remaining.length} أسئلة بدون إجابة</h2><p>الأسئلة المتروكة لا تحصل على نقاط.</p><div class="review-actions"><button id="returnMissing" class="review-primary">ارجع للأسئلة المتروكة</button><button id="finishAnyway">إنهاء وإظهار النتيجة</button></div>`);view.querySelector('#returnMissing').onclick=()=>{a.index=qs.findIndex(q=>!q.sourceIssue&&!a.responses[q.id]);save();render();};view.querySelector('#finishAnyway').onclick=finish;}else finish();}else{a.index++;save();render();focus();}};view.querySelector('#saveExit').onclick=()=>{save();home();};}
function finish(){const a=state.active;if(a.finished)return result(a);a.summary=summarize(questions(),a.responses);a.finished=true;a.finishedAt=new Date().toISOString();state.history.push(JSON.parse(JSON.stringify(a)));if(a.summary.percent>=80&&state.sound!==false){try{feedbackAudio.achievement();}catch{}}save();result(a);focus();}
function result(a){const qs=a.ids.map(id=>MATH_QUESTIONS.find(q=>q.id===id)),s=a.summary,miss=qs.filter(q=>!q.sourceIssue&&!a.responses[q.id]?.pending&&!a.responses[q.id]?.correct.every(Boolean));const previous=state.history.filter(h=>h!==a&&h.startedAt!==a.startedAt&&h.mode===a.mode&&h.ids.join()===a.ids.join()).at(-1);base(`<h1 tabindex="-1">${s.percent===100?'أتقنت المراجعة يا ياسر!':s.percent>=80?'كفو يا ياسر، نتيجة ممتازة!':'كل محاولة تقرّبك من الإتقان'}</h1><div class="review-panel"><div class="review-score">${s.correct} / ${s.total} · ${s.percent}٪</div><p>صحيح: ${s.correct} · خطأ: ${s.wrong} · متروك: ${s.unanswered}${s.pending?' · بانتظار التقييم: '+s.pending:''}${s.selfReviewed?' · تقييم ذاتي: '+s.selfReviewed:''}${s.excluded?' · خارج الدرجة: '+s.excluded:''}</p>${previous&&s.percent>previous.summary.percent?`<p>تحسّنت ${s.percent-previous.summary.percent} نقطة مئوية عن محاولتك السابقة!</p>`:''}<div class="review-actions">${miss.length?'<button id="mistakes" class="review-primary">تدرّب على أخطائك والمتروك</button>':''}<button id="newAttempt">محاولة جديدة</button><button id="reviewHome">صفحة ${esc(REVIEW.label)}</button><button id="resultHistory">سجل مراجعة ${esc(REVIEW.label)}</button></div></div><h2>مراجعة إجاباتك</h2>${qs.map(q=>{const r=a.responses[q.id];return `<article class="review-result-item"><strong>${esc(q.prompt)}</strong>${questionGraphic(q)}<p>${q.sourceIssue?'لا يدخل الدرجة':!r?'متروك':r.pending?'بانتظار المقارنة بالنموذج':r.correct.every(Boolean)?'صحيح':'تحتاج مراجعة'}${r?.selfReviewed?' · تقييم ذاتي':''}</p>${q.fields.map((f,i)=>`<p>${esc(f.label)} · إجابتك: ${esc(r?.values[i]||'—')}<br>الإجابة المعتمدة: ${esc(f.answer)}</p>`).join('')}${q.sourceIssue?`<p>${esc(q.sourceIssue)}</p>`:''}${q.selfReview&&r?.pending?selfReviewControls(q):''}${q.source.quote?`<p>من المراجعة: ${esc(q.source.quote)}</p>`:''}${links(q.page)}</article>`;}).join('')}`);bindSelfReview(a);view.querySelector('#mistakes')?.addEventListener('click',()=>start('train',miss.map(q=>q.id)));view.querySelector('#newAttempt').onclick=home;view.querySelector('#reviewHome').onclick=home;view.querySelector('#resultHistory').onclick=()=>{historyScreen();focus();};}
function openReview({onBack:back}={}){onBack=back;state=load();if(!document.querySelector('link[data-module-style="math-grade6"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='src/modules/yasser/reviews/math-grade6.css';l.dataset.moduleStyle='math-grade6';document.head.append(l);}view=document.getElementById(REVIEW.id==='math'?'yasserMathReviewView':'yasserGrade6ReviewView');if(!view){view=document.createElement('section');view.id=REVIEW.id==='math'?'yasserMathReviewView':'yasserGrade6ReviewView';view.className='view';document.querySelector('#introView').parentElement.append(view);}document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v===view));document.body.classList.remove('intro-mode','hub-mode','yasser-science-mode','yasser-quran-mode');home();window.scrollTo(0,0);}

return {openReview};
}
