export const KHALED_CURRICULUM_META=Object.freeze({
  id:'sa-grade1-math-1448',
  grade:1,
  locale:'ar-SA',
  schoolYear:'1448-1449',
  sourceStructure:'Chapters 1-6 cross-checked against the published Saudi Grade 1 mathematics F1 1448 index; chapters 7-13 remain aligned to the latest 1447 reference pending current-year publication/verification',
  verificationStatus:'chapters 1-6 verified against the 1448 index; chapters 7-13 pending current-year edition verification',
  coverageNote:'Interactive practice targets core lesson skills; textbook page reproduction and handwriting-tracing tasks are outside this app scope'
});

export const KHALED_SKILLS=Object.freeze([
  {id:'classify-compare',chapter:1,title:'المقارنة والتصنيف',shortTitle:'تصنيف • يساوي • أكثر وأقل',symbol:'◉',status:'ready',activityTypes:['classify-one-property','classify-two-properties','equality-groups','compare-groups'],lessons:['التصنيف وفق خاصية واحدة','أحل المسألة: أمثلها','التصنيف وفق أكثر من خاصية','يساوي','أكثر من وأقل من'],goals:['يصنف وفق خاصية واحدة','يمثل المسألة بصريًا ضمن أنشطة التصنيف والمقارنة','يصنف وفق خاصيتين معًا','يفهم تساوي مجموعتين','يميز المجموعة الأكثر','يميز المجموعة الأقل']},
  {id:'numbers-0-5',chapter:2,title:'الأعداد حتى 5',shortTitle:'0 إلى 5 • عد وقراءة',symbol:'5',status:'ready',activityTypes:['count-select','spoken-number-select'],lessons:['الأعداد 1،2،3','قراءة الأعداد 1،2،3 وكتابتها','العددان 4،5','قراءة العددين 4،5 وكتابتهما','قراءة العدد صفر وكتابته'],goals:['يعد عناصر مجموعة حتى 5','يربط الكمية بالعدد الصحيح','يتعرف الرقم عند سماع اسمه','يميز الصفر بصريًا']},
  {id:'position-pattern',chapter:3,title:'الموقع والنمط',shortTitle:'موقع • قبل وبعد • أنماط',symbol:'◆',status:'ready',activityTypes:['position-select','pattern-next'],lessons:['فوق وتحت','أعلى وأوسط وأسفل','قبل وبعد','تحديد الأنماط','إنشاء الأنماط','أحل المسألة: أبحث عن نمط'],goals:['يميز فوق وتحت','يميز أعلى وأوسط وأسفل','يفهم قبل وبعد','يكمل نمطًا بسيطًا','ينشئ نمطًا بسيطًا','يبحث عن نمط ويستخدمه لإكمال المسألة']},
  {id:'numbers-6-10',chapter:4,title:'الأعداد حتى 10',shortTitle:'6 إلى 10 • مقارنة وترتيب',symbol:'10',status:'ready',activityTypes:['count-select','spoken-number-select','number-compare','number-order','ordinal-select'],lessons:['الأعداد 6،7،8','قراءة الأعداد 6،7،8 وكتابتها','العددان 9،10','قراءة العددين 9،10 وكتابتهما','أحل المسألة: أرسم صورة','مقارنة الأعداد حتى 10','ترتيب الأعداد حتى 10','العدد الترتيبي'],goals:['يعد عناصر مجموعة حتى 10','يتعرف الأرقام 6 إلى 10 عند سماعها','يقارن عددين حتى 10','يكمل ترتيبًا عدديًا حتى 10','يميز الموضع الترتيبي']},
  {id:'numbers-11-20',chapter:5,title:'الأعداد حتى 20',shortTitle:'11 إلى 20 • مقارنة وترتيب',symbol:'20',status:'ready',activityTypes:['count-select','spoken-number-select','number-compare','number-order'],lessons:['العددان 11،12','الأعداد 13،14،15','العددان 16،17','أحل المسألة: أبحث عن نمط','الأعداد 18،19،20','مقارنة الأعداد حتى 20','ترتيب الأعداد حتى 20'],goals:['يعد عناصر من 11 إلى 20','يتعرف الأعداد حتى 20 عند سماعها','يقارن عددين حتى 20','يكمل ترتيبًا عدديًا ضمن 20']},
  {id:'addition-foundations',chapter:6,title:'الجمع',shortTitle:'قصص • جمل • تكوين • جمع رأسي',symbol:'+',status:'ready',activityTypes:['visual-addition','addition-sentence','zero-addition','number-bond','vertical-addition'],lessons:['قصص الجمع','تمثيل الجمع','جمل الجمع','الجمع إلى الصفر','أحل المسألة: أمثلها','تكوين الأعداد 4،5،6','تكوين الأعداد 7،8،9','تكوين الأعداد 10،11،12','الجمع الرأسي'],goals:['يفهم ضم مجموعتين','يربط الصورة بجملة جمع','يفهم أن إضافة الصفر لا تغير العدد','يكمل جزءًا مفقودًا لتكوين عدد','يقرأ الجمع الرأسي ويجد الناتج']},
  {id:'subtraction-foundations',chapter:7,title:'الطرح',shortTitle:'قصص • جمل • صفر والكل • طرح رأسي',symbol:'−',status:'ready',activityTypes:['visual-subtraction','subtraction-sentence','zero-whole-subtraction','vertical-subtraction'],lessons:['قصص الطرح','تمثيل الطرح','جمل الطرح','طرح الصفر والكل','أحل المسألة: أرسم صورة','الطرح من الأعداد 4،5،6','الطرح من الأعداد 7،8،9','الطرح من الأعداد 10،11،12','الطرح الرأسي'],goals:['يفهم الأخذ من مجموعة','يربط قصة الطرح بجملة عددية','يفهم طرح الصفر وطرح الكل','يطرح ضمن 12','يقرأ الطرح الرأسي ويجد الناتج']},
  {id:'add-sub-strategies',chapter:8,title:'طرائق الجمع والطرح',shortTitle:'عد أمامي وخلفي • خط أعداد • جملة عددية',symbol:'↔',status:'ready',activityTypes:['count-on-addition','number-line-addition','count-back-subtraction','number-sentence','number-line-subtraction'],lessons:['الجمع بالعد التصاعدي','الجمع باستعمال خط الأعداد','الطرح بالعد التنازلي','أحل المسألة: أكتب جملة عددية','الطرح باستعمال خط الأعداد'],goals:['يستخدم العد التصاعدي لإيجاد ناتج جمع','يستخدم خط الأعداد للجمع','يستخدم العد التنازلي للطرح','يميز الجملة العددية الصحيحة','يستخدم خط الأعداد للطرح']},
  {id:'place-value',chapter:9,title:'القيمة المنزلية',shortTitle:'آحاد وعشرات • حتى 100 • تقدير • مقارنة وترتيب',symbol:'10|1',status:'ready',activityTypes:['place-value-model','place-value-clue','number-to-50','number-to-100','estimate-nearest-ten','compare-to-100','order-to-100'],lessons:['الآحاد والعشرات','أحل المسألة: أخمن ثم أتحقق','الأعداد حتى 50','الأعداد حتى 100','التقدير','مقارنة الأعداد حتى 100','ترتيب الأعداد حتى 100'],goals:['يمثل العدد بالعشرات والآحاد','يستنتج عددًا من خاناته','يتعرف الأعداد حتى 100','يختار تقديرًا قريبًا','يقارن عددين حتى 100','يرتب أعدادًا حتى 100']},
  {id:'measurement',chapter:10,title:'القياس',shortTitle:'طول • وحدات • كتلة • سعة',symbol:'↕',status:'ready',activityTypes:['length-compare','nonstandard-length','measurement-guess-check','mass-compare','capacity-compare'],lessons:['مقارنة الأطوال وترتيبها','وحدات الطول غير القياسية','أحل المسألة: أخمن ثم أتحقق','مقارنة الكتل وترتيبها','مقارنة السعات وترتيبها'],goals:['يقارن بين طولين','يقيس بوحدات غير قياسية','يخمن قياسًا ثم يتحقق','يقارن الكتل','يقارن سعات الأوعية']},
  {id:'number-patterns',chapter:11,title:'أنماط الأعداد',shortTitle:'عشرات • لوحة المئة • عد قفزي',symbol:'↗',status:'ready',activityTypes:['count-by-tens','find-number-pattern','hundred-chart','skip-count'],lessons:['العد بالعشرات','أحل المسألة: أبحث عن نمط','لوحة المئة','العد القفزي: اثنينات، خمسات، عشرات'],goals:['يعد بالعشرات','يكتشف نمطًا عدديًا بسيطًا','يحدد العدد التالي أو الواقع أسفل عدد في لوحة المئة','يعد قفزيًا بالاثنينات والخمسات والعشرات']},
  {id:'geometry-fractions',chapter:12,title:'الأشكال الهندسية والكسور',shortTitle:'مجسمات • أشكال • نصف • ثلث • ربع',symbol:'◒',status:'ready',activityTypes:['solid-identify','solid-classify','geometry-pattern','plane-solid-classify','plane-shape-identify','equal-parts','fraction-select'],lessons:['المجسمات','تصنيف المجسمات: يتدحرج، يتراص، ينزلق','أحل المسألة: أبحث عن النمط','الأشكال المستوية والمجسمات','الأشكال المستوية','الأجزاء المتطابقة','النصف','الثلث والربع'],goals:['يتعرف المجسمات الأساسية','يصنف المجسمات حسب الحركة والتراص','يكمل نمطًا هندسيًا','يميز الشكل المستوي من المجسم','يتعرف الأشكال المستوية','يميز الأجزاء المتطابقة','يتعرف النصف','يتعرف الثلث والربع']},
  {id:'money',chapter:13,title:'النقود',shortTitle:'ريال • عد النقود • مبالغ متساوية • استعمال النقود',symbol:'﷼',status:'ready',activityTypes:['money-recognition','count-money','money-model','equal-money-amounts','use-money'],lessons:['النقود: ريال واحد، ريالان، 5 ريالات، 10 ريالات','عد النقود','أحل المسألة: أمثلها','المبالغ المتساوية','استعمال النقود'],goals:['يتعرف قيم النقود الأساسية في الدرس','يعد مجموعة نقود ويجد مجموعها','يمثل مبلغًا بنقود مناسبة','يميز المبالغ المتساوية','يختار نقودًا تساوي ثمنًا محددًا']}
]);

export function getKhaledSkill(id){return KHALED_SKILLS.find(skill=>skill.id===id)||null;}
export function getReadyKhaledSkills(){return KHALED_SKILLS.filter(skill=>skill.status==='ready');}
