import { createAdaptiveQuestions, createExamQuestions, shuffle } from '../domain/question-bank.js';
import { recordAttempt } from './attempt-service.js';
export function createSession({mode,state,selectedTables,customQuestions=null,startedAt=new Date().toISOString()}){const questions=customQuestions||(mode==='exam'?createExamQuestions(selectedTables,30):createAdaptiveQuestions(state,selectedTables,15));return{mode,selectedTables:[...selectedTables],questions,index:0,correct:0,wrong:0,streak:0,bestStreak:0,answers:[],startedAt,currentQuestionStartedAt:Date.now(),locked:false,lastWeak:[]};}
export function getCurrentQuestion(session){return session?.questions?.[session.index]||null;}
export function submitSessionAnswer({session,state,answer,now=Date.now()}){if(!session||session.locked)return{accepted:false};const numericAnswer=Number(answer);if(!Number.isFinite(numericAnswer))return{accepted:false};const question=getCurrentQuestion(session);if(!question)return{accepted:false};session.locked=true;const responseMs=Math.max(0,now-session.currentQuestionStartedAt),attempt=recordAttempt(state,{question,answer:numericAnswer,responseMs});session.answers.push(attempt);if(attempt.isCorrect){session.correct++;session.streak++;session.bestStreak=Math.max(session.bestStreak,session.streak);}else{session.wrong++;session.streak=0;if(session.mode==='practice'){const insertAt=Math.min(session.questions.length,session.index+3+Math.floor(Math.random()*3));session.questions.splice(insertAt,0,{...question});}}session.index++;return{accepted:true,attempt,done:session.index>=session.questions.length};}
export function unlockNextQuestion(session){session.locked=false;session.currentQuestionStartedAt=Date.now();}
export function buildSessionRecord(session,{incomplete=false,endedAt=new Date().toISOString()}={}){return{mode:session.mode,selected:[...session.selectedTables],startedAt:session.startedAt,endedAt,completed:session.answers.length,correct:session.correct,wrong:session.wrong,bestStreak:session.bestStreak,incomplete,answers:[...session.answers]};}
export function getWeakQuestions(session,limit=6){const counts=new Map();session.answers.filter(a=>!a.isCorrect).forEach(a=>{const key=`${a.table}×${a.multiplier}`;counts.set(key,(counts.get(key)||0)+1);});return[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([key,count])=>{const[table,multiplier]=key.split('×').map(Number);return{table,multiplier,count};});}
export function createWeakPracticeQuestions(weakQuestions,repetitions=3){const questions=[];weakQuestions.forEach(({table,multiplier})=>{for(let i=0;i<repetitions;i++)questions.push({table,multiplier});});return shuffle(questions);}
